chore: update action.

diff --git a/.github/workflows/run_cli_nestjs.yml b/.github/workflows/run_cli_nestjs.yml
--- a/.github/workflows/run_cli_nestjs.yml
+++ b/.github/workflows/run_cli_nestjs.yml
@@ -57,3 +57,8 @@ jobs:
       - name: Conditional Step Example
         if: ${{ fromJson(github.event.inputs.components).graphql.enabled == true }}
         run: echo "GraphQL is enabled. Performing GraphQL specific tasks..."
+
+      - name: Force failure (test)
+        run: |
+          echo "Forcing workflow failure for test"
+          exit 1
